name: firebase
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  firebase_core: ^1.16.0
  firebase_auth: ^3.3.17
  google_fonts: ^2.3.2
  provider: ^6.0.2
  flutter_signin_button: ^2.0.0
  google_sign_in: ^5.3.2
  lottie: ^1.3.0

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.9.2"
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "Assets/images/panda.jpeg"

  flutter_lints: ^1.0.0


flutter:
  uses-material-design: true
 
  assets:
    - Assets/images/
  
  